### ISSUE TITLE
Formally publish as a Grafana Data Source

### ISSUE THREAD

**Issue by v1gnesh** [IBM/RMF#117]
Is this doable? I see at least one IBM data source in Grafana's site...

**Comment by DNikolaevAtRocket** [comment]
Hi @v1gnesh,

Do you mean to sign the plugin and publish it in the Grafana plugin catalog?
If so, it's not feasible at the moment, given the price they want for it.

**Comment by v1gnesh** [comment]
Okay, thanks for the answer :)
