### ISSUE TITLE
Grafana 10.4.0 ****ERROR End*******

### ISSUE THREAD

**Issue by JavaPerformance** [IBM/RMF#42]
Hi, I'm getting this on our new z/OS 3.1 and Grafana 10.4.0

logger=plugin.ibm-rmf-datasource t=2024-04-10T07:03:41.282093291Z level=error msg="\n\n****ERROR @ Time (UTC): 2024-04-10 07:03:41.28184118 +0000 UTC*****\nError logged for error id: pvCxcScShJ, severity: S, err_code: ERR_DDS_ERROR, details: DDSError - GPM0507I (Sev: 3) DDS could not retrieve valid data for the specified date and time range, stackTrace: goroutine 26627 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0xa0\ngithub.com/IBM/RMF/grafana/rmf-app/pkg/plugin/error_handler.(*ErrHandler).LogErrorAndReturnErrorInfo(0xc000954348, {0xfbac08, 0x1}, {0xe4bb0e, 0xd}, {0xfc24e0, 0xc000725dc0})\n\t/home/runner/work/RMF/RMF/grafana/rmf-app/pkg/plugin/error_handler/error_handler.go:101 +0x35c\ngithub.com/IBM/RMF/grafana/rmf-app/pkg/plugin/client.(*RMFClient).getErrorInternal(0xc0004ab4d8, {0xfc24e0, 0xc000725dc0})\n\t/home/runner/work/RMF/RMF/grafana/rmf-app/pkg/plugin/client/client.go:636 +0x182\ngithub.com/IBM/RMF/grafana/rmf-app/pkg/plugin/client.(*RMFClient).query_tabledata(0xc0004ab4d8, 0xc000876700, 0xc001374cc0, 0xc00065b9e0)\n\t/home/runner/work/RMF/RMF/grafana/rmf-app/pkg/plugin/client/client.go:627 +0x308\ncreated by github.com/IBM/RMF/grafana/rmf-app/pkg/plugin/client.(*RMFClient).query in goroutine 26616\n\t/home/runner/work/RMF/RMF/grafana/rmf-app/pkg/plugin/client/client.go:242 +0x622\n\n****ERROR End*******\n"

**Comment by DNikolaevAtRocket** [comment]
Hi @JavaPerformance,

The error simply means that DDS has no data for the requested time range.
The same `GPM0507I` should be reported by frontend as well.

If the data is actually there in DDS (e.g. you can see it accessing DDS directly), then it may be a bug of the plugin.
Would you be able to check if the range you request in Grafana doesn't return data in DDS?

Please note that Grafana Web UI works with the browser local time, while DDS expects ranges in timezone on the z/OS system.

**Comment by JavaPerformance** [comment]
In the RMF WebUI it reports GPM0507I as you say "data missing" ... essentially we IPL'd this morning and therefore it fails reporting any time period that bounds the IPL rather that reporting 0.00 for the missing time period.

Any suggestions as to a fix?

**Comment by DNikolaevAtRocket** [comment]
I suspect that your z/OS Data Gatherer writes data only to storage buffer utilizing no VSAM data sets.
Those can be used to make it store collected data persistently.

That's a good starting point: https://www.ibm.com/docs/en/zos/3.1.0?topic=rmfgat-defining-vsam-data-sets

**Comment by JavaPerformance** [comment]
Is there a way I can write an exit program to write every SMF record to prometheus as it is cut?

**Comment by JavaPerformance** [comment]
Also.... the code should be able to cope with gaps and write zeroes....

**Comment by JavaPerformance** [comment]
> Also.... the code should be able to cope with gaps and write zeroes....

But the whole UI fails when there are gaps in the data....  if I query 5 days of data and we had a 5 minute IP in day 3 then I get no data at all.. "****ERROR End***********"

**Comment by JavaPerformance** [comment]
Also it can take up to 30 minutes to render a graph.

**Comment by DNikolaevAtRocket** [comment]
Okay, what version of the RMF Grafana plugin are you using?

GPM0507I and similar could break time series views in older versions.
The GPM0507I in the description is for table report due to stacktrace; it shouldn't break any UI in either version for full reports.

> Also it can take up to 30 minutes to render a graph.

Well, if you requested 5 days of data for a time series, that's a heavy amount of data to fetch from DDS.

**Comment by JavaPerformance** [comment]
We should take this offline....

**Comment by DNikolaevAtRocket** [comment]
Closing it for the time being. We can re-open it once we get more details to work with.
